inherit_from: "configs/rgbd/iisyFusion/base_config.yaml"

Dataset:
  dataset_path: "datasets/iisyFusion/1-dark-tr"
  flange_poses_file: "datasets/iisyFusion/1-dark-tr/robot_data/flange_poses.txt"
  Calibration:
    fx: 600
    fy: 600
    cx: 426
    cy: 246
    k1: 0
    k2: 0
    p1: 0
    p2: 0
    k3: 0
    distorted: False
    width: 848
    height: 480
    depth_scale: 1000.0
