inherit_from: "configs/rgbd/iisyFusion/base_config.yaml"

Dataset:
  dataset_path: "datasets/iisyFusion/4-natural-tr"
  flange_poses_file: "datasets/iisyFusion/4-natural-tr/robot_data/flange_poses.txt"
  Calibration:
    fx: 599.599
    fy: 599.215
    cx: 426.636
    cy: 246.347
    k1: 0
    k2: 0
    p1: 0
    p2: 0
    k3: 0
    distorted: False
    width: 848
    height: 480
    depth_scale: 1000.0
